# Generated by Django 3.2.4 on 2021-07-08 22:10

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('body', models.TextField()),
                ('snippet', models.CharField(max_length=350)),
                ('date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name')),
                ('overview', models.TextField()),
                ('program', models.CharField(choices=[('BSc', "Bachelor's Degree"), ('MSc', "Master's Degree"), ('PhD', 'Doctorate Degree')], max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to=None)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=234, null=True)),
                ('students', models.IntegerField(blank=True, null=True)),
                ('financial_aid', models.TextField()),
                ('hostel', models.TextField()),
                ('has_hostel', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Name of Scholarship', max_length=150, unique=True)),
                ('description', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('requirements', models.TextField(verbose_name='Application requirements')),
                ('snippets', models.CharField(max_length=350)),
                ('website', models.URLField(blank=True, help_text='Enter scholarship application website link', max_length=350, unique=True)),
                ('whatsapp', models.URLField(blank=True, help_text='Enter scholarship Whatsapp link', max_length=350, unique=True)),
                ('instagram', models.URLField(blank=True, help_text='Enter scholarship Instagram link', max_length=350, unique=True)),
                ('facebook', models.URLField(blank=True, help_text='Enter scholarship Faceook link', max_length=350, unique=True)),
                ('twitter', models.URLField(blank=True, help_text='Enter scholarship Twitter link', max_length=350, unique=True)),
                ('date', models.DateField()),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='core.school')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='title')),
                ('program', models.CharField(choices=[('Undergrad', 'Undergraduate Degree'), ('Postgrad', 'Post graduate Degree'), ('Doctorate', 'Doctorate Degree')], max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title', max_length=150, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='title')),
                ('category', models.CharField(help_text='Enter Name of category', max_length=150, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('info', models.TextField()),
                ('snippet', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.school')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Name of Faculty', max_length=150, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='core.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Department name', max_length=150, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='core.faculty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='core.article')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
