# Generated by Django 3.2.4 on 2021-07-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210710_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
