# Generated by Django 3.2.4 on 2021-07-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentaccount_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='States',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='state',
            field=models.CharField(default=11, max_length=225),
            preserve_default=False,
        ),
    ]
