# Generated by Django 3.2.4 on 2021-06-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210629_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='Institution',
            new_name='institution',
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Application deadline'),
        ),
    ]
