# Generated by Django 3.2.4 on 2021-07-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('tution_fees', models.IntegerField(blank=True, default=0, null=True)),
                ('requirements', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('program_options', models.CharField(choices=[('phD', 'Doctorate'), ('ms', 'Masters'), ('bs', 'Bachelors'), ('dip', 'Diploma')], max_length=200, null=True)),
                ('study_option', models.CharField(blank=True, choices=[('fulltime', 'Full Time'), ('parttime', 'Part Time'), ('both', 'Both')], max_length=233, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='school.school')),
            ],
        ),
    ]
